name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: |
        flutter --version
        flutter config --enable-web
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: setup nodenv & yarn
      run: |
        # install nodenv
        git clone https://github.com/nodenv/nodenv.git ~/.nodenv
        echo 'export PATH="$HOME/.nodenv/bin:/usr/local/bin:/usr/bin:/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(nodenv init -)"' >> ~/.bashrc
        source ~/.bashrc && echo "$PATH"
        # curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-doctor | bash
        nodenv install 8.16.0 && $(cd functions && nodenv local 8.16.0)
        # install yarn & dependencies
        npm install -g yarn && yarn install
        cd functions && yarn install
    - name: setup configuration files
      run: |
        echo "${{ secrets.LocalDart }}" | base64 --decode > flt/lib/local.dart
        echo "${{ secrets.LocalTs }}" | base64 --decode > functions/src/local.ts
    - name: flutter test
      run: cd flt; flutter analyze; flutter test
    - name: build Cloud Functions
      run: echo "$PATH"; cd functions; yarn lint; yarn build
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ job.status }}
