name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: |
        flutter --version
        flutter config --enable-web
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: |
        npx @nodenv/nodenv-installer && export PATH=~/.nodenv/bin:$PATH
        nodenv init && nodenv install 8.16.0
        npm install -g yarn && yarn install
        cd functions && nodenv local 8.16.0 && yarn install
    - name: setup configuration files
      run: |
        echo "${{ secrets.LocalDart }}" > flt/lib/local.dart
        echo "${{ secrets.LocalTs }}" > functions/src/local.ts
    - name: flutter test
      run: cd flt; flutter analyze; flutter test
    - name: build Cloud Functions
      run: |
        export PATH=~/.nodenv/bin:$PATH && nodenv init
        cd functions; yarn lint; yarn build
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ job.status }}
